### ISSUE TITLE
Update to iOS 7 style

### ISSUE THREAD

**Issue by jasonmcdermott** [ParsePlatform/LoginAndSignUpTutorial#5]
I'd like to style the login & signup interface so it matches the visual style & design of iOS 7 (my app uses standard UIKit objects, e.g. UIButton).  Is there a visual update in the works for PFSignUpViewController or PFLoginViewController?

Or is there a way that I can reset the visual elements to use the default iOS 7 styling?

thanks,
Jason

**Comment by hramos** [comment]
ParseUI with iOS 7 style was released a few months ago.
