### ISSUE TITLE
"Tutorial on using the login and signup views" link mentioned in your documentation is broken since 24th January 2015 and doesn't appear anymore in the iOS tutorial list on the Parse website.

### ISSUE THREAD

**Issue by alino91** [ParsePlatform/LoginAndSignUpTutorial#9]
"Tutorial on using the login and signup views" link mentioned in your documentation is broken since 24th January 2015 and doesn't appear anymore in the iOS tutorial list on the Parse website, which is blocking and freaking annoying for beginners and others confirmed developers who need to consult this tutorial. 

Url in question: https://parse.com/tutorials/login-and-signup-views

For more information, please consult the screen shots.

![c](https://cloud.githubusercontent.com/assets/5431357/5889656/ceb19a3c-a432-11e4-8731-884c0359f468.png)

![d](https://cloud.githubusercontent.com/assets/5431357/5889657/d3a1e128-a432-11e4-93de-d85a4c8b9b77.png)

**Comment by nlutsenko-fb** [comment]
Thanks for the report!
Looks like it's back it online now.
